apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: agricloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: umamaayyubi817/agricloud-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: backend-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: agricloud
type: Opaque
stringData:
  DATABASE_URL: "postgresql://agricloud_user:agricloud@12345@postgres:5432/agricloud_db"
  SECRET_KEY: "9ff76571f10f54169cf8cd194b639917fa9a83d7f22902fac89a52b949f5fe96"
  WEATHER_API_KEY: "1162b25b7432dda997586eb4643c0cbe"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "1440"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: agricloud
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
